version: '3'
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: "rails-test-db"
      LANG: C.UTF-8
      LANGUAGE: en_US
    ports:
      - "4316:3306" # ホストからゲストへポートフォワード
    volumes:
      - mysql_data:/var/lib/mysql # MysqlDBの永続化
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    tty: true
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからwebを実行する
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/workdir # ソースコード変更したらDocker側も即反映されるように
volumes:
  mysql_data:
    driver: local
